### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by mojtabas74** [hojjatjafary/CafebazaarUnity#1]
Hi, is this plugin secured from hack?
Application like lucky patcher can hack it or not?

**Comment by hojjatjafary** [comment]
This is only a Unity plugin that let you call Cafebazaar IAB services and does not any other thing, it only do one job and try to do it right.
A local plugin can not prevent your application from cracking if you need to prevent your application or game from cracking you need to implement some of the application logics servers side.

**Comment by mojtabas74** [comment]
Thx
