### ISSUE TITLE
کرش پروژه نمونه

### ISSUE THREAD

**Issue by peyman1959** [hojjatjafary/CafebazaarUnity#10]
با عرض سلام و خسته نباشید
پروژه نمونه ای که خودتون گذاشتین رو با یونیتی 2019.1.3 خروجی گرفتم به محض باز کردن برنامه تو گوشی کرش میکنه

**Comment by Hossynkoala** [comment]
کلا مشکل داره این ماجرا برای یونیتی 2019 برای منم وقتی کار کردم کرش میکرد

**Comment by peyman1959** [comment]
این انگار یسری فایل رو میخواد دانلود کنه که نمیتونه
رفتم از توی یکی از پروژه های قبلی فایلایی که گرفته بود رو کپی کردم اورد تو پروژه جدیده قشنگ خروجی گرفت کارم میکنه

**Comment by Hossynkoala** [comment]
منظورتونو متوجه نشدم چه چیز هایی رو دانلود کنه؟؟ منظورتون همون قسمتی هست که فایل جر میخواد ساخته بشه ؟؟یا اینکه موقع اجرا چون مشکل من خروجی میگیرم ولی توی گوشی اجرا میشه کرش میشه حتی اگه امپرت هم نشه جایی

**Comment by peyman1959** [comment]
توی فولدر اندروید داخل پلاگینز
قبلا بعد از خروجی یسری فایل جر دانلود میکرد میزاشت
اونا رو کپی کنید داخل فولدر اندروید مشکلش حل میشه
هم خروجی گرفتن هم کرش پروژه بعد از خروجی

**Comment by Hossynkoala** [comment]
امکانش هست کل اس دی کی دارین استفاده میکنی رو برام ایمیل کنی؟
برای من چیزی دانلود نمیکنه و اینکه کرش میشه هرکاری میکنم 
hossynassghary@gmail.com
