### ISSUE TITLE
Compatibility with version 2019

### ISSUE THREAD

**Issue by Hossynkoala** [hojjatjafary/CafebazaarUnity#12]
The new sdk is not compatible with the 2019 Unity version and causes the engine to crash

**Comment by mohsen-srn** [comment]
#14

you should remove following tag from manifest:

		<activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<meta-data android:name="unityplayer.UnityActivity" android:value="true" />
			<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
		</activity>
and insert this tag inside application tag:

                            <activity
				android:label="@ref/0x7f020000"
				android:name="com.unity3d.player.UnityPlayerActivity"
				android:launchMode="2"
				android:screenOrientation="1"
				android:configChanges="0x40003fff"
				android:hardwareAccelerated="false">

			<intent-filter>

				<action
						android:name="android.intent.action.MAIN" />

				<category
						android:name="android.intent.category.LAUNCHER" />
			</intent-filter>

			<meta-data
					android:name="unityplayer.UnityActivity"
					android:value="true" />

			<meta-data
					android:name="android.notch_support"
					android:value="true" />
		</activity>
