### ISSUE TITLE
having androidManifest causes crash on app start

### ISSUE THREAD

**Issue by virtouso** [hojjatjafary/CafebazaarUnity#13]
hi. 
i just started using your plugin.
when i have androidManifest like you have in your example, app craashes on start and when i remove it i receive this error:
`java.lang.SecurityException: Not allowed to bind to service Inten`

**Comment by Hossynkoala** [comment]
sdk bazar is not working and their answer is that we are not developing for Unity SDK

**Comment by mohsen-srn** [comment]
I fixed this issue and created a pull request. i hope owner of this project inspect and merge.
problem was with the main activity that is defined in the manifest.
#https://github.com/hojjatjafary/CafebazaarUnity/pull/14

you should **remove** following tag from manifest:

```
		<activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<meta-data android:name="unityplayer.UnityActivity" android:value="true" />
			<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
		</activity>
```

and **insert** this tag inside application tag:


```
                            <activity
				android:label="@ref/0x7f020000"
				android:name="com.unity3d.player.UnityPlayerActivity"
				android:launchMode="2"
				android:screenOrientation="1"
				android:configChanges="0x40003fff"
				android:hardwareAccelerated="false">

			<intent-filter>

				<action
						android:name="android.intent.action.MAIN" />

				<category
						android:name="android.intent.category.LAUNCHER" />
			</intent-filter>

			<meta-data
					android:name="unityplayer.UnityActivity"
					android:value="true" />

			<meta-data
					android:name="android.notch_support"
					android:value="true" />
		</activity>
```

**Comment by Hossynkoala** [comment]
محسن جان امکان داره برای من ارسال کنی اس دی کی که تغییر دادی رو ممنون 
hossynassghary@gmail.com

**Comment by virtouso** [comment]
@mohsen-srn  great job. thanks. unfortunately i used bobardo plugin on my project but hope your work helps other developers.
