### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by Hossynkoala** [hojjatjafary/CafebazaarUnity#16]
دوتا پیشنهاد دارم برای اضافه کردن به اس دی کی که میتونم در پاره وقت  انجام بدم در صورت استقبال شما فورک میگیرم برای کار  

اول ارسال ایمیل به توسعه دهنده در زمان خرید ها که به احتیاج می باشد و برای کسانی که بک اند ندارند کاربرد دارد

دوم  ساخت بک اند ذخیره سازی که به دو بخش 
اولی ساخت سرور ساید برای ذخیره 
دوم ساخت اس دی کی برای ذخیره اطلاعات 
به نظرم این دوتا بخش اضافه بشه خیلی کمک میکنه

**Comment by hojjatjafary** [comment]
از پیشنهاد شما تشکر می کنم

پیشنهاد هایی که دادین رو می شه در لایه بالاتر یا در یونیتی انجام داد لزومی نداره مستقیما در این پروژه انجام بشه
به هر حال
ترجیح من این هست که این پروژه یک کار رو انجام بده و اون کار رو درست انجام بده
قرار نیست این اس دی کی خیلی پیچیده بشه

**Comment by Hossynkoala** [comment]
بله حرف شما کاملا منطقی هست و قبول دارم حرف شمارو
