### ISSUE TITLE
NullPointerException on unity 2019.2.11f1

### ISSUE THREAD

**Issue by sajedn** [hojjatjafary/CafebazaarUnity#17]
Hi, 
first of all tnx for this great SDK, but since unity version 2019.2.11f1 it crashes, error log:

11-09 17:11:20.139   522   569 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
11-09 17:11:20.248  5301  5362 E Unity   : AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
11-09 17:11:20.248  5301  5362 E Unity   : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
11-09 17:11:20.248  5301  5362 E Unity   :      at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:168)
11-09 17:11:20.248  5301  5362 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-09 17:11:20.248  5301  5362 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
11-09 17:11:20.248  5301  5362 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
11-09 17:11:20.248  5301  5362 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:103)
11-09 17:11:20.248  5301  5362 E Unity   :      at android.os.Looper.loop(Looper.java:214)
11-09 17:11:20.248  5301  5362 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
11-09 17:11:20.248  5301  5362 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00041] in <157db3d40e194fc2b8370dbe68a88be2>:0
11-09 17:11:20.248  5301  5362 E Unity   :   at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.St

**Comment by Hossynkoala** [comment]
این ارور ها هنگام خروجی گرفتن براتون هست یا وقتی دارین پکیج امپورت میکنین؟؟

**Comment by sajedn** [comment]
بعد از خروجی گرفتن، روی لاگ کت

**Comment by Hossynkoala** [comment]
من از نو  یبار اس دی کی نصب کردم روی کار جدیدمون و استفاده کردم همین الان بدون مشکل ریلیز میده 
ریلیز آخری که نصب کردم از اس دی کی این بوده:
https://github.com/hojjatjafary/CafebazaarUnity/releases/tag/1.0.4
خود پکیج رو بگیر 
و اینکه یونیتی هم یه سری دستکاری ها توی این کلاس انجام داده ولی تغییر آنچنانی نبوده روش  بازم یبار کل پروژه پکیج کن بک آپ بگیر بعد روی پروژ] جدید امپورت کن پروژتو اگه حل نشدش یبار بدون ایمپورت پروژه خروجی بگیر توی محیط جدید من هر 2 روش الان برای تست و جواب به شما تست کردم هربار ریلیز کامل میده

**Comment by sajedn** [comment]
ممنون، تست میکنم نتیجه رو اطلاع میدم

**Comment by Hamed1984** [comment]
حاجی منم همین مشکل و دارم
قبلا درست بود حالا که میخوایم بازی رو بدیم بیرون به این مشکل برخوردیم
من از آخرین نسخه تپسل هم استفاده می کنم میشه یه تست بکنی ببینی باتپسل مشکلی نداره؟
به نسخه gson ربطی نداره؟

**Comment by Hossynkoala** [comment]
> حاجی منم همین مشکل و دارم
> قبلا درست بود حالا که میخوایم بازی رو بدیم بیرون به این مشکل برخوردیم
> 
> مجبور شدم دانگرید کنم به ورژن 2019.2.9
> شاید مشکل از یونیتی باشه و تو ورژن های بعدی برطرف بشه
> شما هم یه چک بکن با نسخه 2019.2.13 مشکل داره

من با نسخه 12 تست کردم  مشکلی نداشت مشکل شما بخاطر تغییر مانیفست هم میشه چون توی ادیت قبلی فرموده بودید که ادغام کردین با تپسل شما من همون پیشنهاد اول رو میدم یبار در نسخه هایی که یونیتی کش نکرده پروژه جدید پکج بگیرین و دوباره ایمپرتش کنید و تست کنید 
چون پکیج ها به مشکل بخورن دوباره پکیج بشن و دوباره ایمپرت بشن بعضی از چیزها درست میشه شما تست کن اگه نشد بگو من یبار با 13 تست کنم براتون اسکیرین شاتی چیزی هم اگه بود بفرستین عالی میشه

**Comment by Hamed1984** [comment]
سلام
تست کردم کلا با نسخه 11و 13 مشکل داره
اگه ممکنه شما هم یه تست بزن ببین اگه مشکل از یونیتی هست یه باگ ریپورت بفرست براشون که تو نسخه بعدی درستش کنند
ممنون

**Comment by Hossynkoala** [comment]
> 
> 
> سلام
> تست کردم کلا با نسخه 11و 13 مشکل داره
> اگه ممکنه شما هم یه تست بزن ببین اگه مشکل از یونیتی هست یه باگ ریپورت بفرست براشون که تو نسخه بعدی درستش کنند
> ممنون

بانسخه 11 تست گرفتم مشکلی نداشت لاگ فایل هم براتون ارسال کردم که روند هارو مشاهده کنید 
نسخه 13 هم تست میکنم اطلاع میدم تو همینجا
[Editor.log](https://github.com/hojjatjafary/CafebazaarUnity/files/3895355/Editor.log)

**Comment by Hamed1984** [comment]
> سلام :)
> بانسخه 11 تست گرفتم مشکلی نداشت لاگ فایل هم براتون ارسال کردم که روند هارو مشاهده کنید
> نسخه 13 هم تست میکنم اطلاع میدم تو همینجا

نمیدونم مشکل از کجاست 
من همین پروژه مونو بدون هیچ تغییری دانگرید میکنم به یونیتی 2019.2.9
کار میکنه

توی این خط کد

static BazaarIAB()
        {
            if (Application.platform != RuntimePlatform.Android)
                return;

            // Get the plugin instance
            using (var pluginClass = new AndroidJavaClass("com.bazaar.BazaarIABPlugin"))
----->>                mPlugin = pluginClass.CallStatic<AndroidJavaObject>("instance");
        }

ارور میده

Exception
     condition : AndroidJavaException: java.lang.NullPointerException
       stackTrace : java.lang.NullPointerException
com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:136)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.String signature, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
UnityEngine._AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
UnityEngine.AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
UnityEngine.AndroidJavaObject.CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
BazaarPlugin.BazaarIAB..cctor () (at <04bc2dae422f4786ac918f863218716e>:0)
Rethrow as TypeInitializationException: The type initializer for 'BazaarPlugin.BazaarIAB' threw an exception.
Skill.IAP.Bazaar.BazaarIAPInterface.Initialize () (at <04bc2dae422f4786ac918f863218716e>:0)
Skill.IAP.IAPManager.Start () (at <04bc2dae422f4786ac918f863218716e>:0)
UnityEngine.Debug:LogException(Exception)
Skill.IAP.IAPManager:Log(Exception)
Skill.IAP.IAPManager:Start()

**Comment by Hossynkoala** [comment]
> 
> 
> > سلام :)
> > بانسخه 11 تست گرفتم مشکلی نداشت لاگ فایل هم براتون ارسال کردم که روند هارو مشاهده کنید
> > نسخه 13 هم تست میکنم اطلاع میدم تو همینجا
> 
> نمیدونم مشکل از کجاست
> من همین پروژه مونو بدون هیچ تغییری دانگرید میکنم به یونیتی 2019.2.9
> کار میکنه
> 
> توی این خط کد
> 
> static BazaarIAB()
> {
> if (Application.platform != RuntimePlatform.Android)
> return;
> 
> ```
>         // Get the plugin instance
>         using (var pluginClass = new AndroidJavaClass("com.bazaar.BazaarIABPlugin"))
> ```
> 
> ----->> mPlugin = pluginClass.CallStatic("instance");
> }
> 
> ارور میده
> 
> Exception
> condition : AndroidJavaException: java.lang.NullPointerException
> stackTrace : java.lang.NullPointerException
> com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source)
> com.unity3d.player.UnityPlayer.nativeRender(Native Method)
> com.unity3d.player.UnityPlayer.c(Unknown Source)
> com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
> android.os.Handler.dispatchMessage(Handler.java:98)
> android.os.Looper.loop(Looper.java:136)
> com.unity3d.player.UnityPlayer$e.run(Unknown Source)
> UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
> UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.String signature, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
> UnityEngine._AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
> UnityEngine.AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
> UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
> UnityEngine.AndroidJavaObject.CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <157db3d40e194fc2b8370dbe68a88be2>:0)
> BazaarPlugin.BazaarIAB..cctor () (at <04bc2dae422f4786ac918f863218716e>:0)
> Rethrow as TypeInitializationException: The type initializer for 'BazaarPlugin.BazaarIAB' threw an exception.
> Skill.IAP.Bazaar.BazaarIAPInterface.Initialize () (at <04bc2dae422f4786ac918f863218716e>:0)
> Skill.IAP.IAPManager.Start () (at <04bc2dae422f4786ac918f863218716e>:0)
> UnityEngine.Debug:LogException(Exception)
> Skill.IAP.IAPManager:Log(Exception)
> Skill.IAP.IAPManager:Start()

با نسخه 13 هم تست کردم خروچی مشکلی نداشت و پیاده سازی شد کامل فکر کنم برای ادغام تپسل باشه با بازار مانیفست تغییر پیدا میکنه
