### ISSUE TITLE
queryInventory Return Empty List

### ISSUE THREAD

**Issue by iskyteam** [hojjatjafary/CafebazaarUnity#18]
Hi

**queryInventory(string[] skus)** Return Empty **List[BazaarPurchase]** .
I saw this malfunction in **Unity plugin**, but I saw it in **React Native (Native android)** too before.
I think the problem is on CafeBazaar App ( server ) Side.

*** other functions work just fine

please let me know your opinion.
thanks.

**Comment by hojjatjafary** [comment]
There should not be such big issue in CafeBazaar app please make sure you read the entire documentation carefully here in github page. You should be logged in to the CafeBazaar app to get the inventory content properly.

**Comment by iskyteam** [comment]
thanks for your reply Hojjat.
I'm programing for 7 years and I Implemented CafeBazaar IAP ( Google IAP, Appstore IAP, ...) and Your documentation is very Practical and detailed. all the functions work great except **queryInventory**.
I think I have to report the problem to the CafeBazaar itself. However, they don't care about the problems, and they refer me to the documentation. :)

> there are many issues in the CafeBazaar app (+server) and this is one of them.
> These problems are due to the fact that after 8 years, they are still using a Chinese ready-made (source-code) system and cannot design a simple AppStore system.

**Comment by hojjatjafary** [comment]
I can suggest you installing some software in your test environment to check the real http requests and their responses.
I did so when I was developing the Plugin and there was no issue with the inventory.
