### ISSUE TITLE
Init problem

### ISSUE THREAD

**Issue by mashahbazi** [hojjatjafary/CafebazaarUnity#19]
I build an apk using this repo sample with unity version 2019.2.10f1. Even your sample doesn't start up IabHelper. And problem is here that any of billing event either supported or not supported doesn't trigger.
Can some one help me??

**Comment by mashahbazi** [comment]
Ok, I found my problem it was my phone.
So I have a new question.
Why this plugin doesn't support some android phone?? while bazzar native android sdk support it and work without any problem??

**Comment by Iman-Sh** [comment]
> Ok, I found my problem it was my phone.
> So I have a new question.
> Why this plugin doesn't support some android phone?? while bazzar native android sdk support it and work without any problem??

Did you find out what was causing the problem?
