### ISSUE TITLE
not clear!!!!

### ISSUE THREAD

**Issue by samii00** [hojjatjafary/CafebazaarUnity#2]
salam chera hich tozihi baraye shoro'e kar ba in file ha nadadid?!
masalan inke che folder ya file ro bayad be proje unity khodemoon ezafe konim!!! 
ba tavajoh be inke hich file ba pasvand **.unitypackage**   ham dar folderha mojood nist.

**Comment by hojjatjafary** [comment]
https://github.com/hojjatjafary/CafebazaarUnity/releases/tag/1.0.3

**Comment by samii00** [comment]
salam
mamnoon az pasokhgoetoon..
chetor mitonam file IabHelper.java ro edit konam va tooye proje jaygozin konam?

**Comment by hojjatjafary** [comment]
Hi,
if you are using Unity game engine only import the *.unitypackage* file and use the C# interfaces, it is not required to compile the project again.

Good luck.

**Comment by samii00** [comment]
ok .. 
i want to check if purchace is from bazaar or not(for example by checking package name) , 
is there a way to do that by using this unity package?

**Comment by hojjatjafary** [comment]
You can change the java sources and compile it using these simple steps:
https://github.com/hojjatjafary/CafebazaarUnity#build-instruction

**Comment by hojjatjafary** [comment]
try using vpn for your internet connection!

**Comment by samii00** [comment]
thanxxxxx.. it work ;)
