### ISSUE TITLE
IL2CPP problem?

### ISSUE THREAD

**Issue by davoodkharmanzar** [hojjatjafary/CafebazaarUnity#20]
سلام و عرض ادب ...
بنظر میرسه این پلاگین تحت
IL2CPP
روی یونیتی 2019.3 اصلا کار نمیده!

پیشنهاد چی هست؟
ممنون.

**Comment by hojjatjafary** [comment]
اگر امکان داره نسخه جدید رو از قسمت 
release
امتحان کنید.
