### ISSUE TITLE
failure while building

### ISSUE THREAD

**Issue by Booyaka-619** [hojjatjafary/CafebazaarUnity#22]
There is an error while I'm trying to build BazaarIAB.jar file.

* What went wrong:
A problem was found with the configuration of task ':lint' (type 'LintGlobalTask').
> No value has been specified for property 'lintClassPath'.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

I would be happy if you help me with this issue.

**Comment by hojjatjafary** [comment]
We are using Gradle 6.0 so I don't know why you get that error! did you changed anything?
Also try using VPN when building with Gradle.

**Comment by Booyaka-619** [comment]
I didn't change anything and used VPN connection.
I've also tried to build on another PC but faced same problem.

**Comment by hojjatjafary** [comment]
Have you defined ANDROID_HOME in your environment variables?

**Comment by Booyaka-619** [comment]
I've update my android studio and problem solved.

**Comment by hojjatjafary** [comment]
Nice,
I always use the command line, so I don't have such issues,
Anyway I'm glad that the issue is resolved.
