### ISSUE TITLE
None of the events triggers

### ISSUE THREAD

**Issue by Iman-Sh** [hojjatjafary/CafebazaarUnity#23]
I built an APK and unfortunately none of the events triggers, even for init(neither supported nor not supported). Even the Demo Scene in the package is not working. What should I do?
Thanks in advance

**Comment by Mahdad-Baghani** [comment]
> 
> 
> I built an APK and unfortunately none of the events triggers, even for init(neither supported nor not supported). Even the Demo Scene in the package is not working. What should I do?
> Thanks in advance

Please be more specific. Here is a quick checklist to follow:

1. the package name of your game should be identical to that package name of the game on CafeBazaar. 
2. Use the "start_logcat" script to debug your app. check if any exceptions are thrown when BazaarIAB is initialized.
3. what version of the cafeBazaar plugin you are using? I encountered a problem where the java plugin would not correctly get initialized and it would lead to null references when trying to use the plugin inside unity. I reported the error and now it is fixed. Make sure you get the latest release, or clone the latest version of the repository and use the bazaarplugin.jar from the latest version, or you could manually build the .jar file your self with gradle.

**Comment by Iman-Sh** [comment]
> > I built an APK and unfortunately none of the events triggers, even for init(neither supported nor not supported). Even the Demo Scene in the package is not working. What should I do?
> > Thanks in advance
> 
> Please be more specific (your unity version and bazaar plugin version are important details). Here is a quick checklist to follow:
> 
> 1. the package name of your game should be identical to that package name of the game on CafeBazaar.
> 2. Use the "start_logcat" script to debug your app. check if any exceptions are thrown when BazaarIAB is initialized.
> 3. what version of the cafeBazaar plugin you are using? I encountered a problem where the java plugin would not correctly get initialized and it would lead to null references when trying to use the plugin inside unity. I reported the error and now it is fixed. Make sure you get the latest release, or clone the latest version of the repository and use the bazaarplugin.jar from the latest version, or you could manually build the .jar file your self with gradle using these [instructions](https://github.com/hojjatjafary/CafebazaarUnity#build-instruction)

Sorry, I forgot to post here that I solved the problem. I tried my game in other phones and the plugin was ok there. So I figure out that my phone is the problem and I noticed that other games with bazaar plugin has the same issue on my phone as well, so I tried a couple thing (updating the bazaar app, ...) but finally removing bazaar and installing it again solved the problem.
