### ISSUE TITLE
Invoke function in ActionExtensions cause error for non unity classes

### ISSUE THREAD

**Issue by Enzx** [hojjatjafary/CafebazaarUnity#26]
[At this line](https://github.com/hojjatjafary/CafebazaarUnity/blob/master/UnityProject/Assets/CafeBazaarIAB/ActionExtensions.cs#L10) developers are forced to use non-static functions from classes that inherit from UnityEngine.Object, I have worked with several teams that experienced an issue with this policy. 
I guess these constraints are implemented for making sure resources are released at the end of the application life cycle. This decision can be handed to the developer.
I've removed this line for some projects and they still work properly.
Is there any other concern behind this constraint?

**Comment by hojjatjafary** [comment]
The `invoke` method is just a **private** extension method that is used internally by the plugin's code to check that everything works as expected and will not impose any constraints on the external codes.
The users of the plugin should subscribe to the static actions that provided in `BazaarIABEventManager.cs` class so they can use both static and non-static methods.

GL,
Hojjat.

**Comment by hojjatjafary** [comment]
As there are no answers to this question for a couple of days, I close it.
