### ISSUE TITLE
Signature verification failed for sku [ ] -1003 purchase signature

### ISSUE THREAD

**Issue by sinanasiriamirbande** [hojjatjafary/CafebazaarUnity#4]
purchase in  cafebazaars payment gateway is successful. but in app i get this error and cant consume my product 
error : Signature Verification failed for sku [...] -1003 purchase signature verification failed

**Comment by hojjatjafary** [comment]
1. Double check your cafebazaar public key.
2. Try signing your app and test purchase with the signed apk.
3. Clear bazaar application's data.
