### ISSUE TITLE
امنیت پلاگین های مشابه؟؟

### ISSUE THREAD

**Issue by davoodkharmanzar** [hojjatjafary/CafebazaarUnity#5]
ضمن عرض ادب ...

پلاگین مشابهی جهت پرداخت موجود هست که ظاهرا از لحاظ پیاده سازی خیلی راحتتره ...

https://github.com/bobardo/Cafebazaar-IAB-Unity

اما سؤال اینجاست که آیا میشه اعتماد کرد؟

**Comment by hojjatjafary** [comment]
از هر پلاگینی که فکر می کنید ساده تر و مطمئن تر هست استفاده کنید
این پلاگین از طرف کافه بازار مورد تایید قرار گرفته است و نظری راجع به سایر پلاگین ها نداریم.

**Comment by davoodkharmanzar** [comment]
خیلی هم عالی ...
برادر میشه این پرداخت درون برنامه ای رو برای بازی
PC
هم استفاده کرد یا فقط روی اندروید جواب میده؟؟
