### ISSUE TITLE
List.isEmpty() in init function

### ISSUE THREAD

**Issue by mammad1985** [hojjatjafary/CafebazaarUnity#7]
hi im getting this error in our game crash reporting tool :

AndroidJavaException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference com.bazaar.util.IabHelper.startSetup(IabHelper.java:267) com.bazaar.BazaarIABPlugin.init(BazaarIABPlugin.java:59) com.unity3d.player.UnityPlayer.nativeRender(Native Method) com.unity3d.player.UnityPlayer.c(Unknown Source) com.unity3d.player.UnityPlayer$d$2.queueIdle(Unknown Source) android.os.MessageQueue.next(MessageQueue.java:211) android.os.Looper.loop(Looper.java:122) com.unity3d.player.UnityPlayer$d.run(Unknown Source) UnityEngine.AndroidJNISafe.CheckException () UnityEngine.AndroidJNISafe.CallVoidMethod (IntPtr obj, IntPtr methodID, UnityEngine.jvalue[] args) UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args) BazaarPlugin.BazaarIAB.init (System.String publicKey) IAPManager.OnEnable () 

do you have any idea what might cause this?
and how to prevent it?

thanks in advance

**Comment by hojjatjafary** [comment]
Please make sure that you have entered a correct rsa public key, also double check your android manifest for the correct Bazaar purchase permissions.

**Comment by mammad1985** [comment]
our game is published with correct RSA and successful purchases have been made.
I see this error in our crash reporting tools .. I don't know how to reproduce it and we didn't have a complaint yet.
i hoped you knew the possible cause of this error so i can prevent any future complaints.

**Comment by hojjatjafary** [comment]
There are also similar issues with google play purchase events, I don't know the root of the issue but I guess it is related to devices that do not installed Bazaar app at all.

https://stackoverflow.com/questions/20763952/iabhelper-startsetup-causes-nullpointerexception
